### PR TITLE
MongoDB Support

### PR DESCRIPTION
**Pull request by ktwrd**
- [x] Account Manager
- [x] Announcement Manager
- [x] Account License Manager
- [x] Release Info Content
- [x] Published Releases
- [x] Support to import JSON "Database" to MongoDB
    - [x] Accounts
    - [x] Announcements
    - [x] `content.json`
        - [x] ReleaseInfoContent
        - [x] Published
    - [x] Account Licenses
- [x] [Desktop Client] Fix any new endpoint changes

### CODE REVIEW

**Comment by ktwrd** [comment]
Fixed fetching all accounts. Infinite loop in `MongoAccountController.GetAllAccounts`

Got confused between the function that has parameters and doesn't have parameters. Silly me!

**Comment by toastxc** [comment]
jsons are very epic

**Comment by ktwrd** [comment]
`ContentManager.ReleaseInfoContent` has been ported to MongoDB. Reading is fine, writing hasn't been validated yet

**Comment by ktwrd** [comment]
It works......

**Comment by ktwrd** [comment]
all that is left to do is to find a solution for hosting the mongodb database in production

**Pull request merged**
